In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [3]:
df = pd.read_csv("kkg.csv",encoding='latin-1')

In [22]:
df

category                                            message Unnamed: 2  \
0         ham  Go until jurong point, crazy.. Available only ...        NaN   
1         ham                      Ok lar... Joking wif u oni...        NaN   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3         ham  U dun say so early hor... U c already then say...        NaN   
4         ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...       ...                                                ...        ...   
5567     spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568      ham              Will Ì_ b going to esplanade fr home?        NaN   
5569      ham  Pity, * was in mood for that. So...any other s...        NaN   
5570      ham  The guy did some bitching but I acted like i'd...        NaN   
5571      ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  spam  
0           NaN        NaN     0  
1           NaN        NaN     0  
2           NaN        NaN     1  
3           NaN        NaN     0  
4           NaN        NaN     0  
...         ...        ...   ...  
5567        NaN        NaN     1  
5568        NaN        NaN     0  
5569        NaN        NaN     0  
5570        NaN        NaN     0  
5571        NaN        NaN     0  

[5572 rows x 6 columns]

In [21]:
df.rename(columns={'v1':'category','v2':'message'},inplace=True)
df

category                                            message Unnamed: 2  \
0         ham  Go until jurong point, crazy.. Available only ...        NaN   
1         ham                      Ok lar... Joking wif u oni...        NaN   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3         ham  U dun say so early hor... U c already then say...        NaN   
4         ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...       ...                                                ...        ...   
5567     spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568      ham              Will Ì_ b going to esplanade fr home?        NaN   
5569      ham  Pity, * was in mood for that. So...any other s...        NaN   
5570      ham  The guy did some bitching but I acted like i'd...        NaN   
5571      ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  spam  
0           NaN        NaN     0  
1           NaN        NaN     0  
2           NaN        NaN     1  
3           NaN        NaN     0  
4           NaN        NaN     0  
...         ...        ...   ...  
5567        NaN        NaN     1  
5568        NaN        NaN     0  
5569        NaN        NaN     0  
5570        NaN        NaN     0  
5571        NaN        NaN     0  

[5572 rows x 6 columns]

In [6]:
df.groupby('category').describe()

message                                                            \
           count unique                                                top   
category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    653  Please call our customer service representativ...   

              Unnamed: 2         \
         freq      count unique   
category                          
ham        30         45     39   
spam        4          5      4   

                                                                 Unnamed: 3  \
                                                        top freq      count   
category                                                                      
ham        bt not his girlfrnd... G o o d n i g h t . . .@"    3         10   
spam                                            PO Box 5249    2          2   

                                            Unnamed: 4                       
         unique                    top freq      count unique      top freq  
category                                                                     
ham           9                     GE    2          6      5  GNT:-)"    2  
spam          1   MK17 92H. 450Ppw 16"    2          0      0      NaN  NaN

In [7]:
df['spam'] = df['category'].apply(lambda x:1 if x=='spam' else 0)

In [8]:
df.head()

category                                            message Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  spam  
0        NaN        NaN     0  
1        NaN        NaN     0  
2        NaN        NaN     1  
3        NaN        NaN     0  
4        NaN        NaN     0

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.message,df.spam,test_size=0.2)

In [10]:
from sklearn.naive_bayes import MultinomialNB


from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [11]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [12]:
clf.score(x_test,y_test)

0.9838565022421525

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(x_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [15]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [16]:
model.predict(v.transform(x_train))

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [17]:
model.score(v.transform(x_test),y_test)

0.9838565022421525